language: rust

sudo: required
services:
  - docker

install:
  - docker build -t colourbot
  - docker run -d -p 127.0.0.1:80:80 -name colourbot colourbot

script:
  - docker ps | grep -q colourbot

rust:
  - nightly
