language: rust
sudo: required
cache: cargo
services:
  - docker
rust:
  - nightly

before_install:
  - openssl aes-256-cbc -K $encrypted_7626713f97d2_key -iv $encrypted_7626713f97d2_iv
    -in config.test.toml.enc -out config.test.toml -d

script:
  - make test

after_success:
  - make coverage TRAVIS_JOB_ID=$TRAVIS_JOB_ID
  - bash ./docker-upload.sh
