language: rust

sudo: required
services:
  - docker

# build and then test docker image.
install:
  - docker-compose start

script:
  - docker exec colour-bot-v2_bin_1 bash -c "cargo test"
  - docker ps | grep -q colour-bot-v2

rust:
  - nightly
