language: rust
sudo: required
cache: cargo
services:
  - docker
rust:
  - nightly

before_install:
  - openssl aes-256-cbc -K $encrypted_7626713f97d2_key -iv $encrypted_7626713f97d2_iv
    -in config.test.toml.enc -out config.test.toml -d

jobs:
  include:
    - stage: test
      script:
        - make test
        - docker-compose -f ./docker-compose.test.yml down

    - stage: coverage
      script:
        - make coverage TRAVIS_JOB_ID=$TRAVIS_JOB_ID

    - stage: uploading
      script: bash ./docker-upload.sh
