language: rust

sudo: required
services:
  - docker

# build and then test docker image.
install:
  - docker-compose up -d

script:
  - docker-compose run bin bash -c "cargo test"
  - docker ps | grep -q colour-bot-v2

rust:
  - nightly
