[package]
authors = ["Navrin <navman360@gmail.com>"]
name = "colour-bot-v2"
version = "0.1.0"

[dependencies]
bigdecimal = "0.0.10"
chrono = "0.4.0"
nom = "3.2.1"
num-traits = "0.1.41"
rand = "0.4.2"
regex = "0.2.5"
serde = "1.0.27"
serde_derive = "1.0.27"
toml = "0.4.5"

[dependencies.diesel]
features = [
    "numeric",
    "postgres",
]
version = "1.0.0"

[dependencies.serenity]
branch = "v0.5.0"
git = "https://github.com/zeyla/serenity"
