[package]
authors = ["Navrin <navman360@gmail.com>"]
name = "colour-bot-v2"
version = "0.1.0"

[dependencies]
serde = "1.0.27"
serde_derive = "1.0.27"
toml = "0.4.5"

[dependencies.serenity]
branch = "v0.5.0"
git = "https://github.com/zeyla/serenity"