version: "3.0"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432"
  bin:
    image: colour-bot-v2-base
    build: .
    environment:
      DATABASE_URL: postgres://colouradmin:password@db:5432/colours
    ports:
      - "7777:7777"
    volumes:
      - ./config.toml:/app/config.toml
      - cargo:/cargo
    depends_on:
      - db

volumes:
  cargo:
    driver: local
  pgdata: {}
