[discord]
token = "XXXXXXXXXXXXXXXXXXX" # required. Discord bot token.
playing_message = "with a rainbow" # Sets the "Playing" message displayed under the bot.

[database]
username = "admin"
password = "password"
address = "127.0.0.1"
port = "5432"
database = "colours"

[server]
static_path = "./path/to/frontend"
env = "development" # or "production"
logging = true