export const App: string;
export const GridItem: string;
export const Header: string;
export const Navigation: string;
export const Sidebar: string;
export const Content: string;
export const Button: string;
export const FailureNotification: string;
export const SuccessNotification: string;
