export const Root: string;
export const List: string;
export const Padding: string;
export const Colour: string;
export const ColourRow: string;
export const ColourExpanded: string;
export const ColourExpandedButton: string;
export const ColourIcon: string;
export const Preview: string;
